[package]
name = "nmt-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.6"
bytes = "1"
serde = { version = "1", optional = true }
borsh = { version = "0.10.0", optional = true }

[features]
default = []
serde = ["dep:serde"]
